name: Backup Firestore

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

env:
  PROJECT_ID: fadfadah-app
  BUCKET: gs://fadfadah-app-backups
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Google Cloud CLI Tools
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Set GCloud CLI project ID
      run: gcloud config set project $PROJECT_ID
    - name: Backup to Cloud Storage
      run: gcloud firestore export $BUCKET
