name: Deploy the website

on:
  push:
    branches:
      - master
    paths-ignore:
      - functions/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - name: Install packages
        run: yarn
      - name: Build the app
        run: yarn build
        env:
          REACT_APP_FIREBASE_API_KEY: AIzaSyC9VQy2EtTg9QBL6vIdws3178CWM136LkE
          REACT_APP_FIREBASE_AUTH_DOMAIN: fadfadah.me
          REACT_APP_FIREBASE_PROJECT_ID: fadfadah-app
          REACT_APP_FIREBASE_STORAGE_BUCKET: fadfadah-app.appspot.com
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: '137606338'
          REACT_APP_FIREBASE_APP_ID: 1:137606338:web:6b8fa2d11138278ab9f75b
          REACT_APP_FIREBASE_MEASUREMENT_ID: G-KFX596R655
          REACT_APP_FIREBASE_FUNCTIONS_REGION: europe-west6

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
