name: Deploy the website

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - name: Install packages
        run: yarn
      - name: Build the app
        run: yarn build
        env:
          REACT_APP_FIREBASE_API_KEY: AIzaSyB9QiKhNpNd0-FXrxSlYShusU_95quET8I
          REACT_APP_FIREBASE_AUTH_DOMAIN: fad-fadah.firebaseapp.com
          REACT_APP_FIREBASE_DATABASE_URL: https://fad-fadah.firebaseio.com
          REACT_APP_FIREBASE_PROJECT_ID: fad-fadah
          REACT_APP_FIREBASE_STORAGE_BUCKET: fad-fadah.appspot.com
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: '514590012549'
          REACT_APP_FIREBASE_APP_ID: 1:514590012549:web:d679963f9c71faebba65ec
          REACT_APP_FIREBASE_MEASUREMENT_ID: G-L6L6JWXE14

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
